### ISSUE TITLE
local SMTP Hosts Settings

### ISSUE THREAD

**Issue by ProjectMyst** [texxasrulez/additional_smtp#1]
The option "'readonly' => true," dosen't work, regardless of it being true or false, it treats it as true all the time.

I also was wondering if it possible to add wildcard for some of the local SMTP hosts settings. i.e.

'%s' => array(
    'host' => 'ssl://smtp.%s:587',
    'smtp_user' => '%u',
    'smtp_pass' => '%p',
    'smtp_helo_host' => 'smtp.mydomain1.tld',
    'smtp_auth_type' => '',
    'no_save_sent_messages' => true,
    'readonly' => true,
  )

%s - would replace the domain name after the '@' from e-mail address provided for the smtp_user or imap_user if smtp_user was set as %u

**Comment by texxasrulez** [comment]
The option "'readonly' => true," is there so non admin users cannot edit the imap or smtp settings within Roundcube and has nothing to do with making your email from other providers to be "read only".  I will make a better note in code describing what the read only option does.
The wildcard thing will not work or at least in my mind wouldn't be worth the time writing code for that since it is extremely simple to add providers via the config.inc.php file which takes the domain portion of identity to add the IMAP and SMTP particulars. The %u and %p is taken from your Roundcube email from the domain providing your Roundcube and will not work on any other domain.
As far as a wildcard for settings on main array, not all webmail providers have same url configuration or even ports for their SMTP and IMAP access points, so this will not work as well.

Is there a certain webmail provider you require to be added? If so just give me the name of the provider and I will make it happen. I have actually been waiting for requests to add more, so it would be my pleasure to add that.

Even though I cannot help you on your requests, I do appreciate your interest in my work and if you feel so inclined, a donation would be appreciated, but not mandatory, as I have recently lost my job and have joined the ranks of the countless millions on this world who are in the same boat as me now. I am a disabled veteran too and so that makes me unsuited for many jobs that I used to be able to do when I was younger. I am lucky to be alone in this world so no one counts on me for their survival except for my puppy dog and like me, he is not picky on what he eats, so we will be just fine. I am ready for these crazy times to be over with. 
I do thank you and I hope you have a great week.
